spring:
  application:
    name: spring-cloud-admin
server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/
    register-with-eureka: true
    #是否从eureka server获取注册信息， 需要
    fetch-registry: true
    #默认从Euraka服务端拉取服务列表的时间间隔
    registry-fetch-interval-seconds: 30