spring:
  application:
    name: zuul-server


eureka:
  client:
    register-with-eureka: true
    #是否从eureka server获取注册信息， 需要
    fetch-registry: true
    #默认从Euraka服务端拉取服务列表的时间间隔
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://euk1.com:7900/eureka/
server:
  port: 8080