spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lining-flying/spring-cloud-config.git
      label: master
server:
  port: 9999
eureka:
  client:
    service-url:
      defaultZone: http://euk1.com:7900/eureka/
